name: cycletowork
description: A new open source app for track bicycle.
publish_to: 'https://github.com/mondora/cycletowork'
version: 1.2.7+88

environment:
    sdk: '>=2.18.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    intl: ^0.19.0
    cupertino_icons: ^1.0.5
    google_fonts: ^6.2.1
    provider: ^6.0.4
    firebase_core: ^2.3.0
    cloud_functions: ^4.0.5
    firebase_auth: ^4.1.3
    google_sign_in: ^6.2.1
    flutter_dotenv: ^5.0.2
    flutter_native_splash: ^2.2.9
    url_launcher: ^6.1.6
    geolocator: ^12.0.0
    geocoding: ^3.0.0
    flutter_svg: ^2.0.10+1
    sliding_up_panel: ^2.0.0+1
    google_maps_flutter: ^2.3.0
    maps_toolkit: ^3.0.0
    shimmer: ^3.0.0
    flutter_inset_box_shadow: ^1.0.8
    share_plus: ^9.0.0
    sqflite: ^2.1.0+1
    uuid: ^4.4.0
    shared_preferences: ^2.2.3
    logger: ^2.3.0
    firebase_messaging: ^14.1.1
    flutter_local_notifications: ^17.1.2
    badges: ^3.1.2
    flutter_otp_text_field: ^1.1.1
    auto_size_text: ^3.0.0
    firebase_crashlytics: ^3.3.7
    app_settings: ^5.1.1
    webview_flutter: ^4.7.0
    path_provider: ^2.0.11
    path: ^1.8.2
    flutter_native_image: ^0.0.6+1
    firebase_storage: ^11.0.6
    camera: ^0.11.0
    permission_handler: ^11.3.1
    image_picker: ^1.1.1
    wakelock_plus: ^1.2.5
    flutter_activity_recognition: ^3.0.0
    package_info_plus: ^8.0.0
    vibration: ^1.7.6
    device_info_plus: ^10.1.0
    firebase_analytics: ^10.0.6
    firebase_app_check: ^0.2.1+8
    fl_chart: ^0.68.0
    google_maps_flutter_android: ^2.8.0
    google_maps_flutter_platform_interface: ^2.6.0
    envied: ^0.5.4+1

dev_dependencies:
    integration_test:
        sdk: flutter
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0
    path_provider_android: ^2.0.20
    envied_generator: ^0.5.4+1
    build_runner: ^2.4.10

flutter:
    uses-material-design: true
    generate: true
    assets:
        - .env
        - assets/images/
        - assets/icons/
        - assets/maps/

flutter_native_splash:
    background_image: assets/images/splash_screen.png
    background_image_dark: assets/images/splash_screen_dark.png
    android_12:
    fullscreen: true
