// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0XYzIGN4znAQyT6cMcUY4hmK_C_RGFiw',
    appId: '1:626275969774:web:f3deeb0fd5f80279c161ff',
    messagingSenderId: '626275969774',
    projectId: 'cycletowork-f0eac',
    authDomain: 'cycletowork-f0eac.firebaseapp.com',
    storageBucket: 'cycletowork-f0eac.appspot.com',
    measurementId: 'G-DELKVC8J7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCbWoSys6vrPn4BY4QISMFfcAxtSAi4Jw',
    appId: '1:626275969774:android:adf09580eac78e30c161ff',
    messagingSenderId: '626275969774',
    projectId: 'cycletowork-f0eac',
    storageBucket: 'cycletowork-f0eac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxlIeQMQkxf4ywILyjok99iwVi_k4JZsw',
    appId: '1:626275969774:ios:2f406ced90994c30c161ff',
    messagingSenderId: '626275969774',
    projectId: 'cycletowork-f0eac',
    storageBucket: 'cycletowork-f0eac.appspot.com',
    iosBundleId: 'com.mondora.cycletowork',
  );

}